apiVersion: apps/v1
kind: Deployment
metadata:
  name: sml-marketplace-app-prd
  namespace: sml-prd
  labels:
    app: sml-marketplace-app-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sml-marketplace-app-prd
  template:
    metadata:
      labels:
        app: sml-marketplace-app-prd
    spec:
      containers:
      - name: sml-marketplace-api-uat
        image: ghcr.io/smlsoft/sml-marketplace-app:sha-ba35a54
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: web-port
          protocol: TCP
        resources:
          requests:
            memory: "512M"
            cpu: "500m"
          limits:
            memory: "512M"
            cpu: "500m"
